### ISSUE TITLE
Versioning strategy

### ISSUE THREAD

**Issue by dusk125** [gopxl/pixel#2]
Before we introduce too many new things, I suggest we create a v1 branch at the current HEAD and cut a v1.0.0 release from that branch.
Then we can update the mod file on dev (and main) to be v2, and all subsequent releases from there will be under the v2.*.* major version.

If we need to backport a bug fix to v1, we'll be able to via the v1 branch, but this branch will be considered the LTS and not receive new features.

**Comment by duysqubix** [comment]
I like this idea, and fully support it. I think we will still need to update the references so that is says `github.com/gopxl/pixel` first right? Or did you plan on leaving it as the original author intended?

@dusk125

**Comment by duysqubix** [comment]
Believe this issue is addressed. 

`v1` branch created. And official v1.0.0 release created. Repo is now in a state to continue onwards. Closing this for now. Reopen if you think its appropriate.
