### ISSUE TITLE
Wonky Coordinate grid

### ISSUE THREAD

**Issue by duysqubix** [gopxl/pixel#41]
Pixel implements it's coordinate grid different than most graphics rendering systems (infact even different from opengl itself.) This complicates any efforts to integrate custom tools and libraries with pixel and is a hindrance to anyone moving from different library/language/api.

 Original issue: https://github.com/faiface/pixel/issues/292

**Comment by duysqubix** [comment]
@dusk125 

I can not remember where we landed on this. I remember discussing that the wonky grid is how the underlying GL libraries actually expect it. Do I remember this right?

**Comment by dusk125** [comment]
I think we landed that Pixel is following the standard and so should continue to have the "wonky" system. 

If there's desire for it, an enhancement could be to have a window option that flips it (essentially apply a Matrix(1,-1) scale)

**Comment by duysqubix** [comment]
got it, thanks for clarifying

**Comment by dusk125** [comment]
Confirmed not wonky; the expectation in OpenGL is that the lower-left hand of the window is 0,0 with up being positive y and right being positive x.
