### ISSUE TITLE
is not a main package

### ISSUE THREAD

**Issue by Tyshaun-l** [gopxl/pixel#87]
when i try to install the package it gave me these errors:
 go install github.com/gopxl/pixel/@latest
go: downloading github.com/gopxl/pixel v1.0.0
go: github.com/gopxl/pixel/@latest: argument must be a clean package path

go install github.com/gopxl/pixel/v2@latest
go: downloading github.com/gopxl/pixel/v2 v2.2.0
package github.com/gopxl/pixel/v2 is not a main package

go get github.com/gopxl/pixel/v2
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.

**Comment by dusk125** [comment]
This is expected, pixel is not meant to be an executable, but a library that you build your own executables from.

Check out the wiki for how to use the library

**Comment by Tyshaun-l** [comment]
Ight thanks
