### ISSUE TITLE
Is there a way to force the window to use Wayland instead of X11? 

### ISSUE THREAD

**Issue by ghost** [gopxl/pixel#88]
The title says it all. I can't find a way to force the use of Wayland instead of X11. I'm currently experimenting with my own app and I was wondering if it's even possible. And if so, could you please provide me with instructions on how? My source code is basically same as in this [chapter](https://github.com/gopxl/pixel/wiki/Pressing-keys-and-clicking-mouse#Zooming)

Thank you

**Comment by bhperry** [comment]
Good question. I don't think there's outright support for wayland built into pixel, but [glfw](https://github.com/go-gl/glfw) has at least partial support for it and pixel is built around that.

**Comment by dusk125** [comment]
@MasterixCZ  if you want to be amazing you could add your suggestion to the wiki!!

**Comment by dusk125** [comment]
@MasterixCZ I *think* you can just edit the wiki and it'll create a PR, ping me if it doesn't work and I can add it
