### ISSUE TITLE
Suggestion for small wiki update.

### ISSUE THREAD

**Issue by DonnyLee** [gopxl/pixel#96]
Section : Drawing shapes with IMDraw
instead of `circle.Push(0)` -> `circle.Push(pixel.ZV)`. 
During learning by doing, i realized circle.Push(0) didn't work so i replaced it with V(0,0).
![image](https://github.com/user-attachments/assets/e8ec1b60-dc7c-4b44-bb21-7c12c3ecfb1c)

**Comment by dusk125** [comment]
Fixed! Thanks for catching this!
