### ISSUE TITLE
Refactor and Enhance Color Handling in Pixel

### ISSUE THREAD

**Issue by duysqubix** [gopxl/pixel#97]
Refactor the color handling in the Pixel library to improve integration with the standard library and address issues with alpha-premultiplied colors. This includes:

* Making pixel.RGBA an alias for color.RGBA to reduce data movement and improve compatibility with standard Go libraries.
* Ensuring that pixel.RGB() accepts floats and pixel.RGBA.Scaled() scales the alpha channel correctly.
* Investigating the interoperability of HSL color calculations within Pixel.
* Ensuring OpenGL shaders handle color blending and alpha-premultiplication correctly.

**Comment by dusk125** [comment]
Dup of #71
