### ISSUE TITLE
Add Support for Minimum Window Size in Pixel

### ISSUE THREAD

**Issue by duysqubix** [gopxl/pixel#98]
Implement support for setting a minimum window size while allowing resizing in the Pixel library. This feature should leverage the existing `glfwSetWindowSizeLimits` function in GLFW. The implementation should include:

* A new window configuration option for setting the minimum size.
* Proper integration with the existing window resizing functionality.
* Ensuring that setting a minimum size prevents windows from being resized to zero dimensions.

**Comment by dusk125** [comment]
Dup of #91
