### ISSUE TITLE
Import PixelUI under the Gopxl Org

### ISSUE THREAD

**Issue by duysqubix** [gopxl/pixel#99]
Revive and update PixelUI to be compatible with the latest version of Pixel. Consider managing PixelUI as a separate extension within the gopxl organization. 

The project should include:

* Updating PixelUI to be compatible with Pixel v2.
* Fixing existing issues and ensuring all functionality works as expected.
* Deciding whether to maintain PixelUI as a core part of Pixel or as a separate extension within the gopxl organization.

**Comment by dusk125** [comment]
Done!
